services:
  app:
    build: .
    container_name: app-container
    environment:
      - DATABASE_URL=postgresql://user@db/messages
    ports:
      - "5050:5050"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: