name: CI Workflow with Docker

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: 'macos-latest' 

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker (in case additional setup is needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
    
      - name: Run tests in Docker container
        run: |
          docker exec -it app-container pytest

      - name: Clean up Docker container
        run: |
          docker stop app-container
          docker rm app-container
          docker stop db-container
          docker rm db-container