name: CI Workflow with Docker

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: 'ubuntu-latest' 
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Start the Docker container using docker-compose
        run: |
          echo "Starting PostgreSQL container..."
          docker-compose up -d
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker exec -i $(docker ps -q -f "name=db") pg_isready -U user -d messages; do
            echo "Waiting for PostgreSQL to start..."
            sleep 5
          done
      - name: Run the table creation script inside the container
        run: | 
          echo "Running the table creation script..."
          docker exec -i $(docker ps -q -f "name=db") psql -U user -d messages < ./init.sql

          echo "Database setup complete!"
          
      - name: Run tests in Docker container
        run: |
          docker exec -it app-container pytest

      - name: Clean up Docker container
        run: |
          docker stop app-container
          docker rm app-container
          docker stop db-container
          docker rm db-container